version: '3.0'

services:
  grafana: &grafana
    build:
      context: ./
      dockerfile: ./.config/Dockerfile
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise-dev} # sync with e2e.Dockerfile if changing defaults
        grafana_version: ${GRAFANA_VERSION:-10.4.0-66703} # sync with e2e.Dockerfile if changing defaults
        livereload_domain: ${LIVERELOAD_DOMAIN:-localhost:35729}
        anon_org_role: ${ANON_ORG_ROLE:-Admin}
    ports:
      - 3000:3000/tcp
    volumes:
#      - ./fixtures/grafana-license.jwt:/etc/grafana/grafana-license.jwt:z
#      - ./src/_mocks_/msw:/usr/share/grafana/public/msw
      - ./dist:/var/lib/grafana/plugins/grafana-docbooks-app
      - ./provisioning:/etc/grafana/provisioning
#    environment:
#      GF_FEATURE_TOGGLES_ENABLE: 'accessControlOnCall'
#      GF_ENTERPRISE_LICENSE_PATH: /etc/grafana/grafana-license.jwt

  e2e:
    <<: *grafana
    profiles:
      - e2e
    volumes:
      - ./fixtures/grafana-license.jwt:/etc/grafana/grafana-license.jwt:z
      - ./src/_mocks_/msw:/usr/share/grafana/public/msw
      - ./dist:/var/lib/grafana/plugins/grafana-docbooks-app
      - ./e2e/provisioning:/etc/grafana/provisioning
